[loggers]
keys=root

[handlers]
keys=timedRotatingFileHandler

[formatters]
keys=simpleFormatter

[logger_root]
#level=ERROR
level=INFO
handlers=timedRotatingFileHandler

[handler_timedRotatingFileHandler]
class=logging.handlers.TimedRotatingFileHandler
level=INFO
formatter=simpleFormatter
args=('/var/log/webproxy.log', 'midnight', 1, 5)

[formatter_simpleFormatter]
format=%(asctime)s.%(msecs)03d  %(levelname)s  %(reponame)s:%(filename)s:%(funcName)s:%(lineno)d  trace_id=%(trace_id)s %(message)s
datefmt=%Y-%m-%d %H:%M:%S